//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18033
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringClient.refMonitoring {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonitoringValues", Namespace="http://schemas.datacontract.org/2004/07/Monitoring")]
    [System.SerializableAttribute()]
    public partial class MonitoringValues : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AusschussmengenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GutmengenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaschinenstatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ausschussmengen {
            get {
                return this.AusschussmengenField;
            }
            set {
                if ((this.AusschussmengenField.Equals(value) != true)) {
                    this.AusschussmengenField = value;
                    this.RaisePropertyChanged("Ausschussmengen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gutmengen {
            get {
                return this.GutmengenField;
            }
            set {
                if ((this.GutmengenField.Equals(value) != true)) {
                    this.GutmengenField = value;
                    this.RaisePropertyChanged("Gutmengen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maschinenstatus {
            get {
                return this.MaschinenstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaschinenstatusField, value) != true)) {
                    this.MaschinenstatusField = value;
                    this.RaisePropertyChanged("Maschinenstatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="refMonitoring.IMonitoringService")]
    public interface IMonitoringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/isAlive", ReplyAction="http://tempuri.org/IMonitoringService/isAliveResponse")]
        bool isAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/CurrentValues", ReplyAction="http://tempuri.org/IMonitoringService/CurrentValuesResponse")]
        MonitoringClient.refMonitoring.MonitoringValues CurrentValues();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitoringServiceChannel : MonitoringClient.refMonitoring.IMonitoringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitoringServiceClient : System.ServiceModel.ClientBase<MonitoringClient.refMonitoring.IMonitoringService>, MonitoringClient.refMonitoring.IMonitoringService {
        
        public MonitoringServiceClient() {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isAlive() {
            return base.Channel.isAlive();
        }
        
        public MonitoringClient.refMonitoring.MonitoringValues CurrentValues() {
            return base.Channel.CurrentValues();
        }
    }
}
